### ISSUE TITLE
libraries changed? errors on compiling

### ISSUE THREAD

**Issue by spants** [olegv142/esp32-bt-serial#2]
Just tried this on a new machine, but unfortunately I cant get it to install. I ran 'make' to set the options previously.
Using OSX....

/Users/myname/Documents/esp/esp32-bt-serial-master/main/spp_vfs_acceptor.c: In function 'spp_read_handle':
/Users/myname/Documents/esp/esp32-bt-serial-master/main/spp_vfs_acceptor.c:110:5: error: implicit declaration of function 'gpio_set_level'; did you mean '_xtos_set_intlevel'? [-Werror=implicit-function-declaration]
     gpio_set_level(BT_CONNECTED_GPIO, BT_LED_CONNECTED);
     ^~~~~~~~~~~~~~
     _xtos_set_intlevel
/Users/myname/Documents/esp/esp32-bt-serial-master/main/spp_vfs_acceptor.c: In function 'esp_spp_cb':
/Users/myname/Documents/esp/esp32-bt-serial-master/main/spp_vfs_acceptor.c:186:34: error: 'ESP_BT_SCAN_MODE_CONNECTABLE_DISCOVERABLE' undeclared (first use in this function); did you mean 'ESP_BT_GENERAL_DISCOVERABLE'?
         esp_bt_gap_set_scan_mode(ESP_BT_SCAN_MODE_CONNECTABLE_DISCOVERABLE);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  ESP_BT_GENERAL_DISCOVERABLE
/Users/myname/Documents/esp/esp32-bt-serial-master/main/spp_vfs_acceptor.c:186:34: note: each undeclared identifier is reported only once for each function it appears in
/Users/myname/Documents/esp/esp32-bt-serial-master/main/spp_vfs_acceptor.c:186:9: error: too few arguments to function 'esp_bt_gap_set_scan_mode'
         esp_bt_gap_set_scan_mode(ESP_BT_SCAN_MODE_CONNECTABLE_DISCOVERABLE);
         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/myname/Documents/esp/esp32-bt-serial-master/main/spp_vfs_acceptor.c:29:
/Users/myname/esp/esp-idf/components/bt/host/bluedroid/api/include/api/esp_gap_bt_api.h:479:11: note: declared here
 esp_err_t esp_bt_gap_set_scan_mode(esp_bt_connection_mode_t c_mode, esp_bt_discovery_mode_t d_mode);
           ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/myname/Documents/esp/esp32-bt-serial-master/main/spp_vfs_acceptor.c: In function 'app_main':
/Users/myname/Documents/esp/esp32-bt-serial-master/main/spp_vfs_acceptor.c:268:5: error: implicit declaration of function 'gpio_pad_select_gpio' [-Werror=implicit-function-declaration]
     gpio_pad_select_gpio(BT_CONNECTED_GPIO);
     ^~~~~~~~~~~~~~~~~~~~
/Users/myname/Documents/esp/esp32-bt-serial-master/main/spp_vfs_acceptor.c:271:5: error: implicit declaration of function 'gpio_set_direction' [-Werror=implicit-function-declaration]
     gpio_set_direction(BT_CONNECTED_GPIO, GPIO_MODE_OUTPUT_OD);
     ^~~~~~~~~~~~~~~~~~
/Users/myname/Documents/esp/esp32-bt-serial-master/main/spp_vfs_acceptor.c:271:43: error: 'GPIO_MODE_OUTPUT_OD' undeclared (first use in this function)
     gpio_set_direction(BT_CONNECTED_GPIO, GPIO_MODE_OUTPUT_OD);
                                           ^~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [spp_vfs_acceptor.o] Error 1
make: *** [component-main-build] Error 2

**Comment by olegv142** [comment]
Fixed

**Comment by limitium** [comment]
Hi, tried to build and met similar errors. Python 3.6, esp-idf 4.1.

```
/Users/limi/Documents/PlatformIO/Projects/esp32-bt-serial/main/spp_vfs_acceptor.c: In function 'spp_read_handle':
/Users/limi/Documents/PlatformIO/Projects/esp32-bt-serial/main/spp_vfs_acceptor.c:110:5: error: implicit declaration of function 'gpio_set_level'; did you mean '_xtos_set_intlevel'? [-Werror=implicit-function-declaration]
     gpio_set_level(BT_CONNECTED_GPIO, BT_LED_CONNECTED);
     ^~~~~~~~~~~~~~
     _xtos_set_intlevel
/Users/limi/Documents/PlatformIO/Projects/esp32-bt-serial/main/spp_vfs_acceptor.c: In function 'esp_spp_cb':
/Users/limi/Documents/PlatformIO/Projects/esp32-bt-serial/main/spp_vfs_acceptor.c:186:34: error: 'ESP_BT_SCAN_MODE_CONNECTABLE_DISCOVERABLE' undeclared (first use in this function); did you mean 'ESP_BT_GENERAL_DISCOVERABLE'?
         esp_bt_gap_set_scan_mode(ESP_BT_SCAN_MODE_CONNECTABLE_DISCOVERABLE);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  ESP_BT_GENERAL_DISCOVERABLE
/Users/limi/Documents/PlatformIO/Projects/esp32-bt-serial/main/spp_vfs_acceptor.c:186:34: note: each undeclared identifier is reported only once for each function it appears in
/Users/limi/Documents/PlatformIO/Projects/esp32-bt-serial/main/spp_vfs_acceptor.c:186:9: error: too few arguments to function 'esp_bt_gap_set_scan_mod'
         esp_bt_gap_set_scan_mode(ESP_BT_SCAN_MODE_CONNECTABLE_DISCOVERABLE);
         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/limi/Documents/PlatformIO/Projects/esp32-bt-serial/main/spp_vfs_acceptor.c:29:
/Users/limi/Documents/PlatformIO/esp/esp-idf/components/bt/host/bluedroid/api/include/api/esp_gap_bt_api.h:479:11: note: declared here
 esp_err_t esp_bt_gap_set_scan_mode(esp_bt_connection_mode_t c_mode, esp_bt_discovery_mode_t d_mode);
           ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/limi/Documents/PlatformIO/Projects/esp32-bt-serial/main/spp_vfs_acceptor.c: In function 'app_main':
/Users/limi/Documents/PlatformIO/Projects/esp32-bt-serial/main/spp_vfs_acceptor.c:268:5: error: implicit declaration of function 'gpio_pad_select_gpio' [-Werror=implicit-function-declaration]
     gpio_pad_select_gpio(BT_CONNECTED_GPIO);
     ^~~~~~~~~~~~~~~~~~~~
/Users/limi/Documents/PlatformIO/Projects/esp32-bt-serial/main/spp_vfs_acceptor.c:271:5: error: implicit declaration of function 'gpio_set_direction' -Werror=implicit-function-declaration]
     gpio_set_direction(BT_CONNECTED_GPIO, GPIO_MODE_OUTPUT_OD);
     ^~~~~~~~~~~~~~~~~~
/Users/limi/Documents/PlatformIO/Projects/esp32-bt-serial/main/spp_vfs_acceptor.c:271:43: error: 'GPIO_MODE_OUTPUT_OD' undeclared (first use in this function)
     gpio_set_direction(BT_CONNECTED_GPIO, GPIO_MODE_OUTPUT_OD);
                                           ^~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [spp_vfs_acceptor.o] Error 1
make: *** [component-main-build] Error 2
```
