### ISSUE TITLE
Baud rate changes

### ISSUE THREAD

**Issue by Retro-Fitt** [olegv142/esp32-bt-serial#4]
Hi,
I have a digital multimeter which is capable of rs232 communucation and i want it to serial monitor with bluetooth. It's protek 506 which is made about 1995 and serial output parameters are:
Speed: 1200 BAUD
Parity: NONE 
DATA BIT: 7 
STOP BIT: 2

![image](https://github.com/olegv142/esp32-bt-serial/assets/5271947/ce212b24-32ff-4259-afe4-dc07e0001462)

Which are very slow on todays standarts. In your readme

`The supported serial baud rates are in the range from 9600 to 1843200`

which is very high speed for my multimeter. Does ESP32 C3 and your firmware supports 1200 baud speed and other parameters?

**Comment by olegv142** [comment]
Hello,
Honestly I have no idea if 1200 baud would work or not. You can just try
it. Please note that my code will not work on ESP32 C3 since C3 does not
have classic BT at all.
With kind regards,
  Oleg.



пт, 19 апр. 2024 г. в 09:39, Retro Fit ***@***.***>:
